########################################
#              FIMECHECK               #
#     Кодер: don1x (vk.com/don1x)      #
#         2 кодер: HegativCheck        #
########################################

messages:
  prefix: '&6&lПРОВЕРКА: &f'
  only-players: 'Команда только для игроков!'
  no-permission: 'У вас недостаточно прав!'
  no-allowed: 'Нет доступных команд.'
  not-found: 'Игрок не в сети!'
  unknown: 'Команда не найдена.'
  start:
    usage: 'Вызвать игрока на проверку: &a/check start <игрок>'
    sender: 'Вы не можете вызвать себя на проверку!'
    bypass: 'У игрока защита от вызовов на проверку!'
    already: 'Игрок уже на проверке!'
    successfully: 'Вы успешно вызвали игрока &a%player% &fна проверку!'
  ally:
    usage: 'Признать игрока невиновным: &a/check ally <игрок>'
    sender: 'Вы не можете себя признать невиновным!'
    already: 'Игрок не на проверке!'
    successfully: 'Вы успешно признали игрока &a%player% &fневиновным!'
    successfully-target: 'Вас признали невиновным;title:&aВас признали чистым%nl%fУдачной игры!'
  confess:
    usage: 'Признаться в использовании читов: &a/check confess'
    already: 'Вы не на проверке!'
  cheatconfirm:
    stoped: 'Вы успешно забанили игрока за читы.'
    already: 'Игрок не на проверке!'
  getloggs:
    usage: 'Посмотреть логи проверок игрока: &a/check getloggs <игрок>'
    successfully: 'Вы успешно посмотрели логи проверок игрока &a%player%'
  reload:
    usage: 'Перезагрузить конфиг - /check reload'
    successfully: 'Вы успешно перезагрузили конфиг!'

check:
  check-target: # сообщение, которые будет писаться игроку, которого вызвали на проверку
    - ''
    - '&f &6&l┏        &c&lПРОВЕРКА!'
    - '&f &6&l⎪ &fВы были вызваны на проверку'
    - '&f &6&l⎪ &fВ подозрении использовании читов'
    - '&f &6&l⎪ '
    - '&f &6&l⎪ &fДо конца проверки: %time%'
    - '&f &6&l⎪ &fПришлите свой дискорд/скайп модератору:'
    - '&f &6&l⎪ &7/m %player% ваш дискорд/скайп'
    - '&f &6&l⎪'
    - '&f &6&l⎪ &fПо истечению времени, Вы будете'
    - '&f &6&l┗ &fЗабанены на &e30 &fдней;title:&6&lПРОВЕРКА %nl% &fСмотри в чат!'
    - ''
  actionbar: '&fОсталось времени: %time%'

format-logs:
  start: |-
    &f &f
    &f &6&l┏ &a[ВЫЗВАН НА ПРОВЕРКУ]
    &f &6&l⎪ &fДата: &e%date%
    &f &6&l⎪ &fИгрок: &e%target%
    &f &6&l┗ &fМодератор: &e%player%
    &f &f

settings:
  cooldown: 900 # длительность проверки (в секундах) (3600 секунд - 15 минут)
  message-delay: 15 # каждые 15 сек будет писаться сообщение о том, что он вызван на проверку
  abilities:
    move: true
    drop: true
    inventory: true
    chat: true
    break: true
    place: true
  confess-commands: # команды при использовании /check confess (во время проверки)
    - 'tempban -s %player% 3d Признание в использовании читов'
  timer-commands: # команды, если таймер закончится
    - 'tempban -s %player% 3d Истечении времени таймера'
  quit-commands: # команды при выходе с сервера во время проверки
    - 'tempban -s %player% 3d Выход с проверки'

time:
  seconds: '&e&l&n%size%&e сек.'
  minutes: '&e&l&n%size%&e мин.'
  hours: '&e&l&n%size%&e час.'
  days: '&e&l&n%size%&e дн.'
  now: '&e&lсейчас'

